#Use for development purposes only!

version: "3.9"
services: 
  api:
    container_name: InvestmentsAPI
    build:
      context: ./api
    depends_on: 
      - db
    volumes: 
      - ./api:/home/app
    ports:
      - 3001:80
    command: npm run watchAndRun

  db:
    image: mysql
    container_name: InvestmentsDB
    env_file: ./db/.env
    ports:
      - 3306:3306
    

